packages:
  - packages/*

shamefullyHoist: true
ignoreWorkspaceRootCheck: true
strictPeerDependencies: false
autoInstallPeers: true
resolutionMode: highest

catalog:
  c12: '^3.3.1'
  defu: '^6.1.4'
  destr: '^2.0.5'
  fs-extra: '^11.3.2'
  pathe: '^2.0.3'
