name: Publish All Packages

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

env:
  NVTON_DEFAULT_CONFIGS: 'true'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Node v18
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: pnpm run build

      - name: Publish to npm
        run: npm i -g npm@^11.5.2 && pnpm run publish-ci ${{ github.ref_name }}
